require('core.plugin_config.gruvbox')
require('core.plugin_config.lsp_config')
require('core.plugin_config.lualine')
require('core.plugin_config.mason-lspconfig')
-- require('core.plugin_config.mason-null-ls')
-- require('core.plugin_config.null-ls')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.nvim-treesitter')
require('core.plugin_config.ctrlp')
require('core.plugin_config.vdebug')
